name: oscs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildDir: '${{github.workspace}}/build'
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo "$buildDir"
    - name: Create build directory
      run: cmake -E make_directory $buildDir
    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B $buildDir -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: cmake --build $buildDir --config Debug
