name: oscs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildDir: '${{github.workspace}}/build'
    steps:
    - name: mkdir
      run: mkdir build
    - name: build
      run: cmake --build ${{buildDir}} -DCMAKE_BUILD_TYPE=Debug --target all
