name: oscs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildDir: '${{github.workspace}}/build'
    steps:
    - name: echo
      run: echo "$buildDir"
    - name: mkdir
      run: mkdir -p $buildDir
    - name: build
      run: cmake  -DCMAKE_BUILD_TYPE=Debug --target all --build $buildDir
